services:
  client-dev:
    container_name: dev-client-789bet
    image: node:16  # Replace with your desired image tag (e.g., node:16)
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV_ENVIROMENT=dev
      - NEXT_PUBLIC_API_URL=https://api.bks1998.online
      - NEXT_PUBLIC_SITE_URL=https://dev.bks1998.online
      - NEXT_TELEMETRY_DEBUG=0
    ports:
      - "3021:3000"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
